apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: timotheeren/kubepods-users:sha-8103db4ea72da179ed1e4e98280ac48e17a697ee
          ports:
            - containerPort: 50051
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: users-postgres-cluster-app
                  key: uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: DESKTOPS_HOST
              value: "http://desktops:50052"
