apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: timotheeren/kubepods-users:sha-fa29d9736349f9d912ede8a7b964b88271557eaf
          ports:
            - containerPort: 50051
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: users-postgres-cluster-app
                  key: uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
