apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: timotheeren/kubepods-users:sha-e54650eb854625f2fc67968b71cbf90c9c1a8a6d
          ports:
            - containerPort: 50051
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: users-postgres-cluster-app
                  key: uri
