apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - users-schema.yaml

configMapGenerator:
  - name: users-schema-config
    files:
      - schemas/schema.hcl
    options:
      disableNameSuffixHash: true
