apiVersion: atlasschemas.db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: users-schema
  namespace: default
spec:
  urlFrom:
    secretKeyRef:
      name: users-postgres-cluster-app
      key: uri
  schema:
    configMapKeyRef:
      name: users-schema-config
      key: schema.hcl
