apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: timotheeren/kubepods-api:sha-067baa43d31c2b1c67749075ff92449762c25ab8
          ports:
            - containerPort: 3001
