apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: timotheeren/kubepods-api:sha-31787e4799e6ce9ad33003009764bf9e77f97ec0
          ports:
            - containerPort: 3001
          env:
            - name: USERS_HOST
              value: "http://users:50051"
