apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: desktops
rules:
  - apiGroups: ["kubepods.com"]
    resources: ["desktops"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
