apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktops
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desktops
  template:
    metadata:
      labels:
        app: desktops
    spec:
      containers:
        - name: desktops
          image: timotheeren/kubepods-desktops:sha-fd699b90ced4f54f6d8bbe337c392c1bd7953076
          ports:
            - containerPort: 50052
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: desktops-postgres-cluster-app
                  key: uri
