apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktops
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desktops
  template:
    metadata:
      labels:
        app: desktops
    spec:
      containers:
        - name: desktops
          image: timotheeren/kubepods-desktops:sha-27c1a73b4a815a0b77314f0a881c51676af1aaa5
          ports:
            - containerPort: 50051
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: desktops-postgres-cluster-app
                  key: uri
