apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktops
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desktops
  template:
    metadata:
      labels:
        app: desktops
    spec:
      containers:
        - name: desktops
          image: timotheeren/kubepods-desktops:sha-6b1bb017bd3d67b181ecdfe3d994dccb6a876417
          ports:
            - containerPort: 50052
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: desktops-postgres-cluster-app
                  key: uri
