apiVersion: v1
kind: Service
metadata:
  name: desktops
  namespace: default
spec:
  selector:
    app: desktops
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
