apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: secret-generator
  namespace: default
spec:
  interval: 5m
  url: oci://ghcr.io/sap/secret-generator-helm/secret-generator
  ref:
    semver: "0.4.95"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: default
spec:
  interval: 15m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: secret-generator
    namespace: default
