syntax = "proto3";

package provisioning;

service ProvisioningService {
  rpc CreateDesktop(CreateDesktopRequest) returns (CreateDesktopResponse);
  rpc GetDesktops(GetDesktopsRequest) returns (GetDesktopsResponse);
  rpc DeleteDesktop(DeleteDesktopRequest) returns (DeleteDesktopResponse);
}

message Desktop {
  string name = 1;
  string distribution = 2;
  string desktop_environment = 3;
}

message CreateDesktopRequest {
  string name = 1;
  string distribution = 2;
  string desktop_environment = 3;
  string username = 4;
}

message CreateDesktopResponse {}

message GetDesktopsRequest {
  string username = 1;
}

message GetDesktopsResponse {
  repeated Desktop desktops = 1;
}

message DeleteDesktopRequest {
  string name = 1;
  string username = 2;
}

message DeleteDesktopResponse {}
