apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: timotheeren/kubepods-ui:sha-3aa8cd8b0b1537e3579499d079a9f5980ea70b78
          ports:
            - containerPort: 3000
          env:
            - name: API_HOST
              value: "http://api:3001"
