apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: timotheeren/kubepods-ui:sha-0381336c3ddf8f6a1b9322c2533022262adef3c3
          ports:
            - containerPort: 3000
          env:
            - name: API_HOST
              value: "http://api:3001"
