apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - users-schema.yaml
  - desktops-schema.yaml
  - app-ingress.yaml
  - jwt-secret.yaml

configMapGenerator:
  - name: users-schema-config
    files:
      - schemas/users-schema.hcl
    options:
      disableNameSuffixHash: true
  - name: desktops-schema-config
    files:
      - schemas/desktops-schema.hcl
    options:
      disableNameSuffixHash: true
