apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
  - apiGroups: ["", "apps", "kubepods.com"]
    resources: ["desktops", "deployments", "services"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
