apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: desktops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: timotheeren/kubepods-operator:sha-1d57035e0c353227469a3a396bf2a90022b04db6
