apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: desktops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: timotheeren/kubepods-operator:sha-748d0d672e767d4440d989943148e4780e0dd61f
