apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: desktops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: timotheeren/kubepods-operator:sha-ba418f618f5f8f493f63e2039afa5406d95a9852
