apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator
  namespace: desktops
rules:
  - apiGroups: ["", "apps", "kubepods.com"]
    resources: ["desktops", "deployments", "services"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
