syntax = "proto3";

package auth;

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc IncrementChronometer(IncrementChronometerRequest) returns (IncrementChronometerResponse);
}

message RegisterRequest {
  string username = 1;
  string email = 2;
  string password = 3;
}
message RegisterResponse {
  string token = 1;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  string token = 1;
}

message UsersTicks {
  string username = 1;
  uint32 tick = 2;
}

message IncrementChronometerRequest {
  repeated UsersTicks users_ticks = 1;
}

message IncrementChronometerResponse {}
