syntax = "proto3";

package info;

service InfoService {
  rpc RemainingTime(RemainingTimeRequest) returns (RemainingTimeResponse);
  rpc GetUserAccount(GetUserAccountRequest) returns (GetUserAccountResponse);
  rpc SaveSettings(SaveSettingsRequest) returns (SaveSettingsResponse);
}

message RemainingTimeRequest {
  string username = 1;
}

message RemainingTimeResponse {
  uint32 utilization = 1;
}

message GetUserAccountRequest {
  string username = 1;
}

message GetUserAccountResponse {
  string email = 1;
  string username = 2;
}

message SaveSettingsRequest {
  string email = 1;
  string username = 2;
  string old_username = 3;
}

message SaveSettingsResponse {}
