apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: users-schema
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: postgresql.cnpg.io/Cluster/default/users-postgres-cluster
spec:
  urlFrom:
    secretKeyRef:
      name: users-postgres-cluster-app
      key: uri
  schema:
    configMapKeyRef:
      name: users-schema-config
      key: users-schema.hcl
