name: UI CI

on:
  push:
    paths:
      - 'ui/**'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: timotheeren/KubePods/.github/workflows/ci.yml@main
    with:
      image: "ui"
    secrets:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
