apiVersion: kubepods.com/v1
kind: Desktop
metadata:
  name: alpine
  namespace: desktops
spec:
  name: alpine
  id: "abcdef"
  distribution: "alpine"
  desktop_environment: "i3"
  max_ram: "1Gi"
  max_cpu: "100m"
